# Internal nav
nav:
 writing: "source_url/writing/"
 gallery: "source_url/gallery/"
 about: "source_url/about/"



#-------------------------------
# Work Section

projects:
- {name: PROVISIONS, folder: 'proj-1', file: 'provisions/index.html'}
- {name: RIVER OAK, folder: 'proj-2', file: 'riveroak/index.html'}
- {name: MORE COMING SOON!, folder: 'proj-3',}





#-------------------------------
# Work Section

whoweare:
- {name: Oliver Thompson Graduated from Valdosta State in 2016 <br> He is the owner head designer and head developer at saunter marketing, folder: 'proj-1', file: 'https://www.instagram.com/olivernewtonthompson/' }
